#couloms law between two point charges
import math
import numpy as np 
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as patches
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import matplotlib.colorbar as colorbar
import matplotlib.ticker as ticker
import matplotlib.collections as collections
import matplotlib.lines as lines
import matplotlib.transforms as transforms
import matplotlib.path as path
import matplotlib.text as text
import matplotlib.figure as figure
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_tkagg as backend_tkagg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_ps as backend_ps
import matplotlib.backends.backend_qt5agg as backend_qt5agg
import matplotlib.backends.backend_qt5 as backend_qt5
import matplotlib.backends.backend_tk as backend_tk
import matplotlib.backends.backend_webagg as backend_webagg
import matplotlib.backends.backend_webagg_core as backend_webagg_core
import matplotlib.backends.backend_agg as backend_agg
import matplotlib.backends.backend_cairo as backend_cairo
import matplotlib.backends.backend_svg as backend_svg
import matplotlib.backends.backend_pdf as backend_pdf
import matplotlib.backends.backend_ps as backend_ps
import matplotlib.backends.backend_qt5agg as backend_qt5agg
import matplotlib.backends.backend_qt5 as backend_qt5
import matplotlib.backends.backend_tk as backend_tk
import matplotlib.backends.backend_webagg as backend_webagg
import matplotlib.backends.backend_webagg_core as backend_webagg_core
import matplotlib.backends.backend_agg as backend_agg